### ISSUE TITLE
NullPointerException when storing media file

### ISSUE THREAD

**Issue by killergerbah** [KamWithK/AnkiconnectAndroid#54]
When calling the store media file endpoint an error is received indicating a NullPointerException. I could not copy the text out of Kiwi Browser so I have attached a screenshot. The storage space used by AnkiConnect Android seems to go up so it looks like the file is persisting but the returned URL is null.

Edit: On debugging I found the following logs:
```
02-25 14:02:31.509  7581  7598 I AnkiDroid: Opening Collection Log
02-25 14:02:31.556  7581  7595 W AnkiDroid: CardContentProvider/ Could not create temporary media file. 
02-25 14:02:31.556  7581  7595 W AnkiDroid: java.io.IOException: File name too long
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:349)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at java.io.File.createTempFile(File.java:2007)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at com.ichi2.anki.provider.CardContentProvider.insertMediaFile(SourceFile:157)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at com.ichi2.anki.provider.CardContentProvider.insert(SourceFile:635)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.content.ContentProvider.insert(ContentProvider.java:1701)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:330)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:168)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.os.Binder.execTransact(Binder.java:1143)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 
02-25 14:02:31.556  7581  7595 W AnkiDroid: java.io.IOException: File name too long
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:349)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at java.io.File.createTempFile(File.java:2007)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at com.ichi2.anki.provider.CardContentProvider.insertMediaFile(SourceFile:157)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at com.ichi2.anki.provider.CardContentProvider.insert(SourceFile:635)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.content.ContentProvider.insert(ContentProvider.java:1701)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:330)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:168)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-25 14:02:31.556  7581  7595 W AnkiDroid: 	at android.os.Binder.execTransact(Binder.java:1143
```

which seems fixable. I will work on a fix.

![Screenshot_20240225-122725](https://github.com/KamWithK/AnkiconnectAndroid/assets/2254858/c13d45a8-19c8-4827-8a94-0da509bbbc43)

**Comment by killergerbah** [comment]
I am working around this by sending shorter file names. This seems to be an OS limitation so there's probably not much that Ankiconnect Android can do besides detecting the problem and sending a more informative error message.
