### ISSUE TITLE
Anki error

### ISSUE THREAD

**Issue by Getroekah** [KamWithK/AnkiconnectAndroid#68]
Hey when I try to to kiwi browser with yomitan I get this error 
Despite it saying that anki droid service is running
Anki error: Couldn't get deck namesjava.lang.Exception: Couldn't get deck names at com.kamwithk.ankiconnectandroid.ankidroid_api.DeckAPI.deckNames(DeckAPI.java:22) at com.kamwithk.ankiconnectandroid.routing.AnkiAPIRouting.deckNames(AnkiAPIRouting.java:140) at com.kamwithk.ankiconnectandroid.routing.AnkiAPIRouting.findRoute(AnkiAPIRouting.java:47) at com.kamwithk.ankiconnectandroid.routing.AnkiAPIRouting.findRouteHandleError(AnkiAPIRouting.java:103) at com.kamwithk.ankiconnectandroid.routing.APIHandler.chooseAPI(APIHandler.java:33) at com.kamwithk.ankiconnectandroid.routing.RouteHandler.get(RouteHandler.java:70) at fi.iki.elonen.router.RouterNanoHTTPD$DefaultStreamHandler.post(RouterNanoHTTPD.java:100) at fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:386) at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596) at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671) at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945) at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192) at java.lang.Thread.run(Thread.java:923) . Details…

**Comment by KamWithK** [comment]
Go through the README properly and if you still have any questions ask on TMW
Only after that post a bug report here please, this looks like a generic mistake somewhere you made

**Comment by Getroekah** [comment]
Just wanted to drop in and mention that I managed to fix this followed everything correctly 
The issue was the fact I was using a Xiaomi phone which blocks some features so After going to the developer menu and disabling miui optimization it works

**Comment by KamWithK** [comment]
> Just wanted to drop in and mention that I managed to fix this followed everything correctly The issue was the fact I was using a Xiaomi phone which blocks some features so After going to the developer menu and disabling miui optimization it works

Yep pretty common problem unfortunately

**Comment by tomsh12345** [comment]
Hi, I have the same issue. Using a boox leaf 2 with Yomitan. I have removed app optimization but still get this same error. Any help would be appreciated, and yes, I have followed the readme properly. Thank you in advance!

**Comment by Getroekah** [comment]
> Hi, I have the same issue. Using a boox leaf 2 with Yomitan. I have removed app optimization but still get this same error. Any help would be appreciated, and yes, I have followed the readme properly. Thank you in advance!

Ok so first step
Is to disable app optimization (this will REMOVE alllll the premissions for will of your apps so you will later have to give all their apps permissions back)
Second go to anki droid disable the API option and enable it back again then follow the readme 
Hope this works for you!

**Comment by KamWithK** [comment]
> Hi, I have the same issue. Using a boox leaf 2 with Yomitan. I have removed app optimization but still get this same error. Any help would be appreciated, and yes, I have followed the readme properly. Thank you in advance!

A couldn't get deck names error can also be caused by a scuffed Yomitan config from desktop

**Comment by KamWithK** [comment]
In general though these problems are always due to the device or (imported) config you use

I don't have your specific devices to test with, but another user might so I can't say it enough times, ask these questions on a language learning Discord server (e.g. The Moe Way)...
